server:
  port: 3000
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/localhost.p12
#    key-store-password: changeit

rt-server:
  port: 9099
  host: 0.0.0.0

info:
  app:
    name: Alumni Backend
    description: This is the alumni backend of my license.
    version: 1.0.0

spring:
  data:
    mongodb:
      authentication-database: admin
mvc:
  throw-exception-if-no-handler-found: true


